Repository NorESMhub/NorESM-docs, pull requests merged in 2024-09, with the labels that each got.

#45 Add NorESM2.5 build status
  README.md
Labels: documentation, new release

#46 Update noresm2.0.8
  access/releases_noresm20.rst
  configurations/platforms.rst
Labels: old release

#47 updated paths for the diagnostic tools
  diagnostics/aero_diag.rst
  diagnostics/diag_run.rst
  diagnostics/esmvaltool.rst
Labels: documentation, old release

#48 Started some documentation for NorESM2.3
  contribute/vc_github.rst
  noresm2.3/noresm2.3_release_notes.rst
Labels: documentation
